server:
  port: 8989
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ashokitschool/configuration_properties

          clone-on-start: true
         
      
      

