spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
      - id: greet-service
        uri: lb://GREET-API
        predicates:
        - Path=/greet
      - id: welcome-service
        uri: lb://WELCOME-API
        predicates:
        - Path=/welcome
  application:
    name: CLOUD-API-GATEWAY
server:
  port: 2222

