server:
  port: 1414

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: monu@1515
    url: jdbc:mysql://localhost:3306/sbms
    username: root
  jpa:
    show-sql: true

